repos:
  - repo: https://github.com/thoughtworks/talisman
    rev: "v1.37.0"
    hooks:
      - id: talisman-commit
        entry: cmd --githook pre-commit
  - repo: https://github.com/PyCQA/bandit
    rev: "1.8.3"
    hooks:
      - id: bandit
        args: [-c, pyproject.toml, -r, -l]
        additional_dependencies: ["bandit[toml]"]
        exclude: 'tests/'
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: "v0.11.12"
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - repo: local
    hooks:
      - id: run-checks
        name: linter
        entry: ./scripts/run_checks.sh
        language: script
        pass_filenames: false
