[tool.poetry]
name = "va-enp-api"
version = "0.0.1"
description = ""
authors = ["VA Enterprise Notification Platform - VA Notify"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
fastapi = {extras = ["standard"], version = "*"}
gunicorn = "*"
python = "^3.12"
uvicorn = {extras = ["standard"], version = "*"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
