services:
  api:
    build:
      context: ..
      dockerfile: ./ci/Dockerfile
      args:
        POETRY_ARGS: --with static_tools,test,mkdocs
        TEST_FOLDER: tests
    container_name: enp-api
    ports:
      - 6012:6012
    entrypoint: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "6012", "--reload"]
    env_file:
      - .env.docker
    volumes:
      - "../app/:/app/app/:rw"
      - "../tests/:/app/tests/:rw"
