services:
  api:
    build:
      context: ..
      dockerfile: ./ci/Dockerfile
      args:
        POETRY_ARGS: --with static_tools,test,mkdocs
        TEST_FOLDER: tests
    container_name: enp-api
    ports:
      - 8000:8000
    entrypoint: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    env_file:
      - .env.local
    volumes:
      - "../app/:/app/app/:rw"
      - "../tests/:/app/tests/:rw"

  enp-db:
    image: postgres:16
    container_name: enp-db
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: LocalPassword
      POSTGRES_DB: va-enp-api-db
