services:
  enp:
    build:
      context: ..
      dockerfile: ./ci/Dockerfile
      args:
        POETRY_ARGS: --with static_tools,test,mkdocs,dev_tools
        TEST_FOLDER: tests
    container_name: enp-api
    ports:
      - 8000:8000
    entrypoint: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    env_file:
      - .env.local
    volumes:
      - "../app/:/app/app/:rw"
      - "../tests/:/app/tests/:rw"

  postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=notification_api
      - POSTGRES_PASSWORD=LocalPassword

networks:
  default:
    name: va-notify
    external: true