services:
  enp:
    build:
      context: ..
      dockerfile: ./ci/Dockerfile
      args:
        POETRY_ARGS: --with static_tools,test,mkdocs,dev_tools
        TEST_FOLDER: tests
    container_name: enp-api
    ports:
      - 8000:8000
    entrypoint: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    env_file:
      - .env.local
    volumes:
      - "../app/:/app/app/:rw"
      - "../tests/:/app/tests/:rw"
    logging:
      driver: loki
      options:
        loki-url: "http://host.docker.internal:3100/loki/api/v1/push"

networks:
  default:
    name: va-notify
    external: true