services:
  db:
    image: postgres:15
    restart: unless-stopped
    ports:
      - 5432:5432
    logging:
      driver: "none"
    environment:
      - POSTGRES_DB=notification_api
      - POSTGRES_PASSWORD=LocalPassword
    ## Anything in the docker-entrypoint-initdb.d folder will be run when the container starts
    volumes:
      - type: bind
        source: ../napi-schema.sql
        target: /docker-entrypoint-initdb.d/napi-schema.sql
        read_only: true

## TODO: Run ENP tests with pytest in a container