services:
  api:
    build:
      context: ..
      dockerfile: ./ci/Dockerfile
    container_name: enp-api
    ports:
      - 8000:8000
    entrypoint: ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    env_file:
      - .env.local
    volumes:
      - "../app/:/app/app/:rw"

  enp-db:
    image: postgres:16
    container_name: enp-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: LocalPassword
      POSTGRES_DB: va-enp-api-db
