name: "ECS Task Render & Deploy"
description: "Renders an ECS task definition from a template (with secret substitutions) and deploys it to ECS. Additionally uploads an environment file."
inputs:
  task-definition-path:
    description: "Path to the ECS Task Definition template file (e.g. task-definition.template.json)"
    required: true
  container-name:
    description: "The container name to update"
    required: true
  image:
    description: "The container image to substitute in the task definition"
    required: true
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-region:
    description: "The AWS region to render and deploy to."
    required: true
  role-to-assume:
    description: 'AWS role to assume'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
          
    - name: Configure VAEC AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.role-to-assume }}
        role-skip-session-tagging: true
        role-duration-seconds: 900

    - name: Upload Env File to S3
      shell: bash
      run: |
        aws s3 cp cd/${ENV}.env s3://vanotify-environment-variables-dev/va-enp-api/

    - name: Pre-render Task Definition
      id: pre_render
      shell: bash
      run: |
        echo "Rendering template with envsubst..."
        # Substitute environment variables in the task definition file
        envsubst < "${{ inputs.task-definition-path }}" > pre-rendered-task-definition.json
    
    - name: Additional Rendering for Double Interpolation
      id: pre_render
      shell: bash
      run: |
        echo "Rendering template with envsubst..."
        # Substitute environment variables in the task definition file
        envsubst < pre-rendered-task-definition.json > task-definition.json

    - name: Render Task Definition
      id: render
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ./task-definition.json
        container-name: ${{ inputs.container-name }}
        image: ${{ inputs.image }}
