name: 'Builds and Push Artifacts'
description: 'Builds and pushes a Docker image'
inputs:
  ref:
    description: 'Git reference (commit SHA, branch, or tag) to build'
    required: true
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-region:
    description: "AWS region to push to"
    required: true
  role-to-assume:
    description: 'AWS role to assume'
    required: true

outputs:
  image-uri:
    description: 'The Docker image URI that was built/pushed'
    value: ${{ steps.set-output.outputs.image-uri }}

runs:
  using: "composite"
  steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}

    - name: Configure VAEC AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.role-to-assume }}
        role-skip-session-tagging: true
        role-duration-seconds: 900

    - name: Login to VAEC ECR
      id: login-ecr-vaec
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: 'true'

    - name: Docker Build
      uses: docker/build-push-action@v6
      with:
        file: ci/Dockerfile
        context: .
        push: true
        tags: ${{ steps.login-ecr-vaec.outputs.registry }}/va_enp_api:${{ inputs.ref }},${{ steps.login-ecr-vaec.outputs.registry }}/va_enp_api:${{ github.sha }} ## Tagging with branch/tag and SHA to maintain SHA record and human readability

    # This step sets the Docker image URI as an output from the composite action
    - name: Set image output
      id: set-output
      shell: bash
      run: |
        # Using the ref tag as our main object to pass around
        echo "image-uri=${{ steps.login-ecr-vaec.outputs.registry }}/va_enp_api:${{ inputs.ref }}" >> $GITHUB_OUTPUT