name: Export Secrets to S3
run-name: "Export Secrets to S3"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  export_secrets:
    name: "export-secrets"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws-us-gov:iam::171875617347:role/project/project-terraform-oidc-role-dev
          aws-region: us-gov-west-1

      - name: Write Secrets to File
        run: |
          cat <<EOF > secrets.env
          AWS_ACCOUNT_NUMBER=${{ secrets.AWS_ACCOUNT_NUMBER }}
          AWS_ARN_REGION=${{ secrets.AWS_ARN_REGION }}
          AWS_REGION=${{ secrets.AWS_REGION }}
          DD_API_KEY=${{ secrets.DD_API_KEY }}
          DEV_TASK_DEFINITION_SECRETS_JSON=${{ secrets.DEV_TASK_DEFINITION_SECRETS_JSON }}
          OIDC_DEPLOY_ROLE_PREFIX=${{ secrets.OIDC_DEPLOY_ROLE_PREFIX }}
          PERF_TASK_DEFINITION_SECRETS_JSON=${{ secrets.PERF_TASK_DEFINITION_SECRETS_JSON }}
          TASK_DEFINITION_SECRETS_JSON=${{ secrets.TASK_DEFINITION_SECRETS_JSON }}
          VAEC_AWS_ACCESS_KEY_ID=${{ secrets.VAEC_AWS_ACCESS_KEY_ID }}
          VAEC_AWS_SECRET_ACCESS_KEY=${{ secrets.VAEC_AWS_SECRET_ACCESS_KEY }}
          VAEC_DEPLOY_ROLE=${{ secrets.VAEC_DEPLOY_ROLE }}
          EOF

      - name: Upload Secrets to S3
        run: |
          aws s3 cp secrets.env s3://vanotify-gh-parameters/${{ github.event.repository.name }}/secrets.env \
            --sse AES256

      - name: Cleanup Secret File
        if: always()
        run: rm -f secrets.env