name: Run Tests

permissions:
  contents: read
  id-token: write

on:
  pull_request:
    branches: [main]
  merge_group:

jobs:
  test:
    name: PR Tests
    uses: ./.github/workflows/test_suite.yml
    with:
        ref: ${{ github.ref }}
    secrets: inherit
